name: Check Format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          source: "./bins ./evaluation ./models ./modules ./optimizer ./preprocessors ./processors ./schedulers ./text ./utils"
